### PR TITLE
update emblem-source and barber-emblem for compatibility to new version of handlebars-rc4

### PR DESCRIPTION
**Pull request by Ehres**
Update middleman-emblem.gemspec for dependency update : 
barber-emblem
emblem-source

### CODE REVIEW

**Comment by pierrickrouxel** [comment]
:+1: 

I experience an error with multiple template rendering. When I try to render 2 templates in 2 named outlet I obtain following error :

> Compiler said: TypeError: Cannot call method 'replace' of undefined

Fixed with this pull request.

**Comment by j-mcnally** [comment]
Yay thanks for the help guys! I will pull this in and push to ruby grms asap. Thanks for the PR

**Comment by pierrickrouxel** [comment]
Hi ! Can you merge the PR please ?

**Comment by j-mcnally** [comment]
Will do this today,

Sorry!

**Pull request closed without merging**
